### ISSUE TITLE
I tried to install taudac on my Raspberry Pi, but the installation failed.

### ISSUE THREAD

**Issue by H-sw123** [taudac/taudac-driver-dkms#2]
I tried to install taudac on my Raspberry Pi, but the installation failed.
Error! The /var/lib/dkms/taudac/2.2.2/5.15.84-v7l+/armv7l/dkms.conf file for the taudac module contains a BUILD_EXCLUSIVE directive that does not match the current kernel and architecture. This indicates that it should not be built.
`pi@raspberrypi:~ $ sudo dkms install -m taudac -v 2.2.2 --force

Creating symlink /var/lib/dkms/taudac/2.2.2/source ->
                 /usr/src/taudac-2.2.2

DKMS: add completed.
Error!  The /var/lib/dkms/taudac/2.2.2/5.15.84-v7l+/armv7l/dkms.conf for module taudac includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux`

**Comment by taudac** [comment]
@H-sw123 Could you retry with current master (d581323a766d3b66e163499c320c52c8e565842f)?

    sudo dkms install -m taudac -v 2.3.7 --force
